services:
  ss24_abnahme:
    build:
      context: .
    image: vvthromildner/vv_abnahme_script:latest
    ports:
      - "9000:9000"
    env_file:
      - .env
    volumes:
      - ./results:/app/results

volumes:
  results:

